renana/osd-github-101

- OSD-Smart/career.md
- OSD-Smart/open-source-day.md
Added another md file and some tips for Open Source Day.
> Updated layout and content

- OSD-Smart/career.md
- OSD-Smart/career_101.md
These are basic first changes. Added another md file in my first OSD project
> my changes

- OSD-Smart/github.txt
hetal's changes - added a new file
> my changes from Git101

- OSD-Smart/career.md
> Pull request test

- code_of_conduct.md
> My first pull request 

- OSD-Smart/newfile.md
> add new file

- OSD-Smart/career.md
I added two tips to the list during vGHC OSD.
> Added 2 more tips to the list

- code_of_conduct.md
> Test Commit Pull Request

- OSD-Smart/contributors.md
> Update contributor file

- OSD-Smart/contributors.md
Adding a contributor for the workshop.
> Adding a contributor

- OSD-Smart/career.md
> Updates to career.md

- OSD-Smart/contributors.md
I added my name to the contributor's file.
> Added my name to Contributors list

- OSD-Smart/career.md
- OSD-Smart/contributors.md
- OSD-Smart/open-source-day.md
> Updated changes as prepration to OSD

- OSD-Smart/career.md
ask google about any problems faced !
> Added a career tip.

- OSD-Smart/career.md
- OSD-Smart/contributors.md
Per commits, added my name to contributors.md, and made some cleanup/adjustments for career.md
> Updated changes as part of OSD tutorial 2021

- OSD-Smart/career.md
- OSD-Smart/contributors.md
Git Hub 101 Committing changes.
> Updated Changes to OSD

- OSD-Smart/career.md
- OSD-Smart/contributors.md
- OSD-Smart/open-source-day.md
Added name and career advice as part of OSD
> Added name and career advice.

- OSD-Smart/contributors.md
I have added my name in the contributor's file in alphabetical order
> Added my name in the contributors file

- OSD-Smart/career.md
- OSD-Smart/contributors.md
> Added my name

- OSD-Smart/contributors.md
> Updated changes as preparation to OSD

- OSD-Smart/contributors.md
> name change

- OSD-Smart/career.md
- OSD-Smart/contributors.md
> Adding name and career advice

- OSD-Smart/contributors.md
- OSD-Smart/open-source-day.md
> Undated changes as preparation to OSD

- OSD-Smart/contributors.md
> Git101 ghc2021

- OSD-Smart/contributors.md
This is my first pull request. I added my name as a contributor inside contributors.md
> added myself as a contributor
